### ISSUE TITLE
Place options screen

### ISSUE THREAD

**Issue by joakim1999** [frostcloud/TGF-Garados#24]
This will show where you are and where you can go to. Also other actions that may be performed.

**Comment by yegorf1** [comment]
I think it will be in stats screen?

**Comment by joakim1999** [comment]
I don't think it will be enough space. I'm already using all the space

**Comment by yegorf1** [comment]
But we need to combine them

**Comment by joakim1999** [comment]
Do we? Why?

**Comment by joakim1999** [comment]
Why can't place thing come after the stats screen? Like in normal games

**Comment by yegorf1** [comment]
Hm... O'kay. Will back to this question later
